### Marcas testes
POST  http://localhost:1234/marca/cadastrar
Content-Type: application/json

{
    "nome": "Renalt"
}

###
GET  http://localhost:1234/marca/listar/609221ca626f1e0b207cd995

### Carro testes
POST  http://localhost:1234/carro/cadastrar
Content-Type: application/json

{
    "modelo": "Monza",
    "placa": "ADF-3355",
    "ano": 1990
}

###
GET  http://localhost:1234/carro/listar

###
GET  http://localhost:1234/carro/listar/ADF-3355

###
DELETE  http://localhost:1234/carro/remover/ADF-3355