### Carro testes
POST  http://localhost:1234/carro/cadastrar
Content-Type: application/json

{
    "modelo": "A2",
    "placa": "AEE-2222",
    "ano": 2015
}

###
GET  http://localhost:1234/carro/buscar/AEE-2222

###
GET  http://localhost:1234/carro/listar

###
PUT  http://localhost:1234/carro/alterar
Content-Type: application/json

{
    "modelo": "A2",
    "placa": "AEE-2222",
    "ano": 2015
}

###
DELETE  http://localhost:1234/carro/remover/AEE-2222