###
POST  http://localhost:1234/carro/cadastrar
Content-Type: application/json

{
    "modelo": "Monza",
    "placa": "ADF-3355",
    "ano": 1990
}

###
GET  http://localhost:1234/carro/listar

###
GET  http://localhost:1234/carro/listar/ADF-3355

###
DELETE  http://localhost:1234/carro/remover/ADF-3355